# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ric0LVcuLkYbUAIaFxT6e0BCNAE8WRjZ
"""

"""
bahrain_agent package

This package contains all the logic for the 🇧🇭 Bahrain Statistical AI Agent:

- Data repository loader
- Query layer for structured analytics
- Description layer for narrative generation
- NLU router for intent classification
- The core BahrainStatsAgent class (the main public interface)

You generally do NOT need to modify this file.
When you add more data or extend functionality, modify the internal modules,
not this top-level interface.
"""

from .agent import BahrainStatsAgent
from .data_layer import load_all_data, DataRepository
from .query_layer import (
    get_workers_by_year,
    get_top_occupations,
    get_households_by_governorate,
    get_latest_density,
    get_housing_units_summary,
    get_students_summary,
    get_teachers_summary,
    get_higher_education_summary,
)
from .describe_layer import (
    describe_labour_market,
    describe_governorates,
    describe_housing_units,
    describe_students,
    describe_teachers,
    describe_higher_education,
)
from .nlu_router import classify_intent, extract_year

__all__ = [
    "BahrainStatsAgent",
    "load_all_data",
    "DataRepository",
    "get_workers_by_year",
    "get_top_occupations",
    "get_households_by_governorate",
    "get_latest_density",
    "get_housing_units_summary",
    "get_students_summary",
    "get_teachers_summary",
    "get_higher_education_summary",
    "describe_labour_market",
    "describe_governorates",
    "describe_housing_units",
    "describe_students",
    "describe_teachers",
    "describe_higher_education",
    "classify_intent",
    "extract_year",
]

