# -*- coding: utf-8 -*-
"""io.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19IkrqwUpaH_3W88cMBpTsb2eb8zSq5Za
"""

# bahrain_agent/utils/io.py
from pathlib import Path
import pandas as pd

def load_csv_safe(root_path, fname):
    path = Path(root_path) / fname
    if not path.exists():
        return None, f"missing:{fname}"
    try:
        df = pd.read_csv(path)
        return df, None
    except Exception as e:
        return None, f"error:{e}"